version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
